---

- name: Restart kong
  systemd:
    daemon_reload: yes
    name: kong
    state: restarted
    enabled: yes

- name: Reload kong
  systemd:
    daemon_reload: yes
    name: kong
    state: restarted
    enabled: yes

- name: Restart postgresql
  systemd:
    name: postgresql
    state: restarted
